# Generated by Django 2.0.5 on 2018-08-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20180809_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=128),
        ),
    ]
