# Generated by Django 2.0.5 on 2018-08-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20180809_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='pattern',
            field=models.CharField(default='', max_length=128),
        ),
    ]
