# Generated by Django 2.0.5 on 2018-08-12 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20180811_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('report_status', models.IntegerField(choices=[(1, '未处理'), (2, '处理中'), (3, '已处理')], default=1)),
                ('report_type', models.IntegerField(choices=[(1, '用詞不當'), (2, '內容重覆'), (3, '無意義內容')], default=1)),
                ('detail', models.TextField(null=True)),
                ('ctime', models.DateTimeField()),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r', to='repository.UserInfo')),
            ],
        ),
    ]
