# Generated by Django 2.0.5 on 2018-08-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_report_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
